# Generated by Django 3.1.7 on 2021-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumer', '0002_auto_20210317_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Job',
            new_name='job',
        ),
        migrations.AddField(
            model_name='contact',
            name='cont2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact 2'),
        ),
    ]
